backend:
  name: git-gateway
  branch: master

media_folder: "/src/images/"
collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "portfolio" # Used in the UI
    folder: "content/portfolio/**" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: "title"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
